### ISSUE TITLE
Allow a more flexible choice of date in `get_ishares_index`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.data.scraping#21]
The function `get_ishares_index` currently pulls indices data from `ishares.com`. Currently, the function parameter `timestamp` is used to determine what data we should be pulling. 

When given the argument `2021Q4`, it converts this to the last date in the quarter, which is "20211231".

This worked well for 2021Q4 data, however it seems that for 2022Q4 doesn't have any data for `20221231` (it does seem to have data for `20221230`).

Perhaps we should make this function more flexible, and parameterize the date itself?

**Comment by AlexAxthelm** [comment]
Since we're using quarters for data preparation, I would suggest a case statement that returns the date we want (in this case `20221230`)
something like:
```r
ishares_date <- function(data_quarter){
  dplyr::case_when(
    data_quarter == "2021Q4" ~ 20211231,
    data_quarter == "2022Q4" ~ 20211231
  )
}
```

and then we can expand that list when we add new quarters.

**Comment by jdhoffa** [comment]
Ok there is even weirder behavior actually. 

Looking at the function description of `get_ishares_index_data()` it looks like it even expects input of the format `20221231`, but it also (maybe accidentally?) accepts input like `2021Q4`. 

What's interesting is that, even if I were to pass it `timestamp = "20211215` as an argument, it would internally convert this date to the last date of the quarter (so `"20211231"`), meaning there is currently no way a user could select any date other than the final date of the quarter.

**Comment by cjyetman** [comment]
> Ok there is even weirder behavior actually.
> 
> Looking at the function description of `get_ishares_index_data()` it looks like it even expects input of the format `20221231`, but it also (maybe accidentally?) accepts input like `2021Q4`.
> 
> What's interesting is that, even if I were to pass it `timestamp = "20211215` as an argument, it would internally convert this date to the last date of the quarter (so `"20211231"`), meaning there is currently no way a user could select any date other than the final date of the quarter.

Yes, this was by (possibly bad) design. I intended to enforce that given a quarter, the last day of that quarter would be used. Otherwise, I think we need some sort of enforcement or validation that an appropriate date is being used for the quarter of the data being prepared. It is complicated by the fact that ishares may or may not have data for the desired last day, in which case some kind of manual decision would need to be made (and hopefully well documented).

**Comment by cjyetman** [comment]
> What kind of enforcements/ validations do you think the `get_ishares_index_data()` function should receive, given that we may need to set the end date `+/- 1 day` or so?

Honestly, I'm not sure... it just feels a bit icky to allow an arbitrary date to be chosen without some strong record of it built in. I think having it in the config is a good step towards that.

**Comment by jdhoffa** [comment]
Yeah, I agree...

We could pass a warning if the date is `>2 days` from the last date of the quarter? I dunno if that is useful at all

**Comment by cjyetman** [comment]
> We could pass a warning if the date is >2 days from the last date of the quarter? I dunno if that is useful at all

That could be useful, though it entails inferring the "timestamp"/quarter from the value itself, which is something I was originally hoping to circumvent, e.g. it would be possible for someone to be trying to create data for 2021Q4 but input a date 20221230 and it would not warn you because 20221230 is < 2 days from the end of 2022Q4 but it doesn't realize that the actual timestamp is 2021Q4.

**Comment by jdhoffa** [comment]
Yeah definitely... but the only way to infer what year you want is fro the argument you pass to `timestamp` (or `as_of_date` now) anyway, so I guess we just need to trust that it's the correct one? I'm not sure

**Comment by cjyetman** [comment]
yeah, before I think I was taking the strategy "don't let it be anything different than what it should be", versus "allow anything, but be clear about what was done and possibly warn about drastically off base options"

**Comment by cjyetman** [comment]
now seeing/remembering that the date used for the download is baked into the output, I feel a bit more comfortable about allowing an arbitrary date

**Comment by cjyetman** [comment]
It's mostly about when someone says "are you sure this data is from xyz date" being able to confidently say "yes".
