### ISSUE TITLE
Consider changing the name of the `index_regions` dataset

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.data.scraping#39]
# DANGEROUS

Likely must be co-ordinated across many repos. Off the top of my head, probably warrants at least looking at:
`pacta.data.preparation`, `portfolio.allocate`, and `pacta.portfolio.report`
and
`workflow.data.preparation` and `workflow.transition.monitor`

cc: @cjyetman any other you can think of?

**Comment by cjyetman** [comment]
probably not so bad... I think it's only on the data.prep side of things these days
https://github.com/search?q=org%3ARMI-PACTA+index_regions+-is%3Aarchived&type=code

**Comment by jdhoffa** [comment]
Awesome. 

I flagged DANGEROUS because it smelled like it might be, and I didn't have the time/ energy to look into it more deeply XD

**Comment by jdhoffa** [comment]
Hmm yeah actually maybe the name is fine, I don't remember why I initially opened this repo, and I didn't add enough context to the ticket. Closing now
