### ISSUE TITLE
implement testing with mocking

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.data.scraping#4]
Implement robust testing for these functions with a mocking package to prevent frequent failures due to frequent hiccups with internet access and web server responses.

related: https://github.com/RMI-PACTA/pacta.data.preparation/issues/167

great resource: https://books.ropensci.org/http-testing/index.html

using one of (in no particular order):
https://docs.ropensci.org/vcr/
https://docs.ropensci.org/webmockr/
https://enpiar.com/r/httptest/
https://enpiar.com/httptest2/
https://webfakes.r-lib.org

**Comment by jdhoffa** [comment]
Transferred to https://github.com/RMI-PACTA/pacta.data.scraping/issues/34
