### ISSUE TITLE
import issues from {pacta.data.preparation}

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.data.scraping#6]
[{pacta.data.preparation}](https://github.com/RMI-PACTA/pacta.data.preparation) had a number of issues related to the functions that have been extracted here. Because one cannot transfer an issue from a private repo to a public repo, we should manually transfer the info from the following issues here.

https://github.com/RMI-PACTA/pacta.data.preparation/issues/282
https://github.com/RMI-PACTA/pacta.data.preparation/issues/278
~https://github.com/RMI-PACTA/pacta.data.preparation/issues/167~ now https://github.com/RMI-PACTA/pacta.data.scraping/issues/4
https://github.com/RMI-PACTA/pacta.data.preparation/issues/166
https://github.com/RMI-PACTA/pacta.data.preparation/issues/164
https://github.com/RMI-PACTA/pacta.data.preparation/issues/172

**Comment by jdhoffa** [comment]
- [ ]  ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/282~ Closed
- [ ] ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/278~ Closed
- [ ] ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/167~ now https://github.com/RMI-PACTA/pacta.data.scraping/issues/4
- [ ] ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/166~ now https://github.com/RMI-PACTA/pacta.data.scraping/issues/35
- [ ] ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/164~ now https://github.com/RMI-PACTA/pacta.data.scraping/issues/37
- [ ] ~https://github.com/RMI-PACTA/pacta.data.preparation/issues/172~ now https://github.com/RMI-PACTA/pacta.data.scraping/issues/36

**Comment by jdhoffa** [comment]
All issues here have been addressed or transferred. Closing this one
